### ISSUE TITLE
Improper working for breakpoint 768 px by tailwind

### ISSUE THREAD

**Issue by Parth909** [CoinPlanet/cp-front#11]
![image](https://user-images.githubusercontent.com/59220026/131255276-38932ab8-991d-4e0c-b9d7-48847ddf4fc9.png)

The css for the grid is 

```css
  @media (max-width: 768px) {
    .dash_grid {
      display: grid;
      grid-template-columns: repeat(10, 1fr);
      grid-template-rows: auto;
      grid-column-gap: 0px;
      grid-row-gap: 0px;
    }

    .dash_section_1 {
      grid-area: 1 / 1 / 2 / 11;
    }
    .dash_section_2 {
      grid-area: 2 / 1 / 3 / 11;
    }
  }

  .dash_side_nav {
    @apply rounded-md inline-flex items-center px-3 py-1 mx-3 bg-gray-100 cursor-pointer hover:text-blue-600 md:bg-gray-50 md:w-full md:my-2 md:py-2 md:hover:bg-blue-100 md:pl-5;
  }
```
